name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package with pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install .

      - name: Execute test command with pipx
        run: |
          smbmap --help